[project]
name = "pdm-project-template"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Cvandia", email = "106718176+Cvandia@users.noreply.github.com"},
]
dependencies = []
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = true

[dependency-groups]
dev = ["pre-commit>=4.0.1"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
